//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.23 at 10:46:01 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://geni-orca.renci.org/xml/node-agent2/AgentConfig", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.renci.nodeagent2.agent.config.xsd;
