//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.23 at 10:46:01 AM EST 
//


package org.renci.nodeagent2.agent.config.xsd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for unitChoice.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="unitChoice"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="week"/&gt;
 *     &lt;enumeration value="day"/&gt;
 *     &lt;enumeration value="hour"/&gt;
 *     &lt;enumeration value="minute"/&gt;
 *     &lt;enumeration value="second"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "unitChoice")
@XmlEnum
public enum UnitChoice {

    @XmlEnumValue("week")
    WEEK("week"),
    @XmlEnumValue("day")
    DAY("day"),
    @XmlEnumValue("hour")
    HOUR("hour"),
    @XmlEnumValue("minute")
    MINUTE("minute"),
    @XmlEnumValue("second")
    SECOND("second");
    private final String value;

    UnitChoice(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static UnitChoice fromValue(String v) {
        for (UnitChoice c: UnitChoice.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
